fix

diff --git a/templates/dev.yml b/templates/dev.yml
--- a/templates/dev.yml
+++ b/templates/dev.yml
@@ -7,7 +7,7 @@ stages:
     displayName: "DEV"
     jobs:
       # 1. Run Security Scans
-      - template: modules/security_scans.yml
+      - template: modules/jobs/security_scans.yml
         
       - job: "Linting" 
         displayName: "Python and Yaml Lint"
@@ -31,98 +31,98 @@ stages:
               yamllint -c cicd_configs/lint/.yamllint . || true
             displayName: "Run YamlLint"
 
-      - job: "ValidateAndDeploy"
-        displayName: "Validate and Deploy Bundle"
-        dependsOn: 
-          - SecurityChecks
-          - Linting
-        variables:
-          - template: variables.yml
-            parameters:
-              environment: ${{ parameters.environment }}
+      # - job: "ValidateAndDeploy"
+      #   displayName: "Validate and Deploy Bundle"
+      #   dependsOn: 
+      #     - SecurityChecks
+      #     - Linting
+      #   variables:
+      #     - template: variables.yml
+      #       parameters:
+      #         environment: ${{ parameters.environment }}
         
-        steps:
-          # 1. Install Agent Requirements & Allowing Executables
-          - script: |   
-              # Exit immediately if any command fails
-              set -e
+      #   steps:
+      #     # 1. Install Agent Requirements & Allowing Executables
+      #     - script: |   
+      #         # Exit immediately if any command fails
+      #         set -e
 
-              # Install the Databricks CLI
-              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
+      #         # Install the Databricks CLI
+      #         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
               
-              # Enable all scripts to be executable within scripts folder
-              chmod +x ./templates/scripts/*
-            displayName: "Install Agent Requirements & Allowing Executables"
+      #         # Enable all scripts to be executable within scripts folder
+      #         chmod +x ./templates/scripts/*
+      #       displayName: "Install Agent Requirements & Allowing Executables"
 
-          # 2. Get and Increment Semantic Version Tag
-          - script: templates/scripts/bump-version.sh
-            name: setTag
-            displayName: "Get and Increment Tag"
+      #     # 2. Get and Increment Semantic Version Tag
+      #     - script: templates/scripts/bump-version.sh
+      #       name: setTag
+      #       displayName: "Get and Increment Tag"
           
-          # 3. Generate Environment Variables
-          - script: |
-              # Exit immediately if any command fails
-              set -e    
+      #     # 3. Generate Environment Variables
+      #     - script: |
+      #         # Exit immediately if any command fails
+      #         set -e    
 
-              # Generate all required variables      
-              export WHL_FILE=cdp_core-$(setTag.BUILD_VERSION)-py3-none-any.whl
-              export SOURCE_PATH=packages/${WHL_FILE}
-              export TARGET_PATH=/Workspace/Shared/artifacts/${WHL_FILE}
-              export BUNDLE_VAR="environment=$(ENVIRONMENT),whl_path=/Workspace/Shared/artifacts/${WHL_FILE},SPN_ID=$(SPN_ID)"
+      #         # Generate all required variables      
+      #         export WHL_FILE=cdp_core-$(setTag.BUILD_VERSION)-py3-none-any.whl
+      #         export SOURCE_PATH=packages/${WHL_FILE}
+      #         export TARGET_PATH=/Workspace/Shared/artifacts/${WHL_FILE}
+      #         export BUNDLE_VAR="environment=$(ENVIRONMENT),whl_path=/Workspace/Shared/artifacts/${WHL_FILE},SPN_ID=$(SPN_ID)"
 
-              # Persist variables 
-              echo "##vso[task.setvariable variable=SOURCE_PATH;isOutput=true]$SOURCE_PATH";
-              echo "##vso[task.setvariable variable=TARGET_PATH;isOutput=true]$TARGET_PATH";
-              echo "##vso[task.setvariable variable=BUNDLE_VAR;isOutput=true]$BUNDLE_VAR";
-            name: setEnvVars
-            displayName: "Setting Environment Variables"
+      #         # Persist variables 
+      #         echo "##vso[task.setvariable variable=SOURCE_PATH;isOutput=true]$SOURCE_PATH";
+      #         echo "##vso[task.setvariable variable=TARGET_PATH;isOutput=true]$TARGET_PATH";
+      #         echo "##vso[task.setvariable variable=BUNDLE_VAR;isOutput=true]$BUNDLE_VAR";
+      #       name: setEnvVars
+      #       displayName: "Setting Environment Variables"
 
-          # 6. Validate Databricks Bundle
-          - template: modules/databricks_azure_cli.yml
-            parameters:
-              servicePrincipal: $(SPN_DEV_NAME)
-              description: "Validating Databricks Bundle"
-              inlineScript: |
-                databricks bundle validate --var=$(setEnvVars.BUNDLE_VAR)
+      #     # 6. Validate Databricks Bundle
+      #     - template: modules/databricks_azure_cli.yml
+      #       parameters:
+      #         servicePrincipal: $(SPN_DEV_NAME)
+      #         description: "Validating Databricks Bundle"
+      #         inlineScript: |
+      #           databricks bundle validate --var=$(setEnvVars.BUNDLE_VAR)
 
-          # 7. Deploy Databricks Bundle
-          - template: modules/databricks_azure_cli.yml
-            parameters:
-              servicePrincipal: $(SPN_DEV_NAME)
-              description: "Deploy Databricks Bundle"
-              inlineScript: |
-                export BUILD_VERSION=$(setTag.BUILD_VERSION)
-                databricks bundle deploy --var=$(setEnvVars.BUNDLE_VAR)
+      #     # 7. Deploy Databricks Bundle
+      #     - template: modules/databricks_azure_cli.yml
+      #       parameters:
+      #         servicePrincipal: $(SPN_DEV_NAME)
+      #         description: "Deploy Databricks Bundle"
+      #         inlineScript: |
+      #           export BUILD_VERSION=$(setTag.BUILD_VERSION)
+      #           databricks bundle deploy --var=$(setEnvVars.BUNDLE_VAR)
 
-                databricks workspace mkdirs /Shared/artifacts
-                databricks workspace import --overwrite --format "AUTO" --file $(setEnvVars.SOURCE_PATH) $(setEnvVars.TARGET_PATH)
+      #           databricks workspace mkdirs /Shared/artifacts
+      #           databricks workspace import --overwrite --format "AUTO" --file $(setEnvVars.SOURCE_PATH) $(setEnvVars.TARGET_PATH)
 
         
-      - job: "UnitTest"
-        displayName: "Unit Tests"
-        dependsOn: 
-          - ValidateAndDeploy
-        variables:
-          - name: BUNDLE_VAR
-            value: $[ dependencies.ValidateAndDeploy.outputs['setEnvVars.BUNDLE_VAR'] ]
-          - template: variables.yml
-            parameters:
-              environment: ${{ parameters.environment }}
-        steps:
-          - script: |   
-              # Exit immediately if any command fails
-              set -e
+      # - job: "UnitTest"
+      #   displayName: "Unit Tests"
+      #   dependsOn: 
+      #     - ValidateAndDeploy
+      #   variables:
+      #     - name: BUNDLE_VAR
+      #       value: $[ dependencies.ValidateAndDeploy.outputs['setEnvVars.BUNDLE_VAR'] ]
+      #     - template: variables.yml
+      #       parameters:
+      #         environment: ${{ parameters.environment }}
+      #   steps:
+      #     - script: |   
+      #         # Exit immediately if any command fails
+      #         set -e
 
-              # Install the Databricks CLI
-              curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
+      #         # Install the Databricks CLI
+      #         curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
               
-            displayName: "Install Agent Requirements"
+      #       displayName: "Install Agent Requirements"
           
-          # 1. Run Unit Tests
-          - template: modules/databricks_azure_cli.yml
-            parameters:
-              servicePrincipal: $(SPN_DEV_NAME)
-              description: "Unit Tests"
-              inlineScript: |
-                databricks bundle run jb_pytest --var=$(BUNDLE_VAR)
+      #     # 1. Run Unit Tests
+      #     - template: modules/databricks_azure_cli.yml
+      #       parameters:
+      #         servicePrincipal: $(SPN_DEV_NAME)
+      #         description: "Unit Tests"
+      #         inlineScript: |
+      #           databricks bundle run jb_pytest --var=$(BUNDLE_VAR)
              
